apiVersion: v1
kind: Service
metadata:
  name: api-svc
spec:
  type: NodePort
  selector:
    app: api-dep
  ports:
  - nodePort: 30333
    port: 8080
    targetPort: otp-port
---
apiVersion: v1
kind: Service
metadata:
  name: otp
spec:
  selector:
    app: otp-dep
  ports:
  - port: 8080
    targetPort: otp-port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otp-dep
spec:
  selector:
    matchLabels:
      app: otp-dep
  template:
    metadata:
      labels:
        app: otp-dep
    spec:
      containers:
      - name: otp-dep
        image: idea456/myjejak-planner-api
        imagePullPolicy: Never
        resources:
          limits:
            memory: "2000Mi"
            cpu: "1000m"
        ports:
        - name: otp-port
          containerPort: 8080
  replicas: 1